//
// AddressVerifySyntaxOnlyResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Syntactic validity of email address */
public class AddressVerifySyntaxOnlyResponse: JSONEncodable {
    /** True if the email address is syntactically valid, false if it is not */
    public var validAddress: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ValidAddress"] = self.validAddress
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
