//
// AddressGetServersResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Result of a partial email address validation */

public struct AddressGetServersResponse: Codable {

    public var success: Bool?
    public var servers: [String]?

    public init(success: Bool?, servers: [String]?) {
        self.success = success
        self.servers = servers
    }

    public enum CodingKeys: String, CodingKey { 
        case success = "Success"
        case servers = "Servers"
    }


}

