//
// AddressVerifySyntaxOnlyResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Syntactic validity of email address */

public struct AddressVerifySyntaxOnlyResponse: Codable {

    /** True if the email address is syntactically valid, false if it is not */
    public var validAddress: Bool?

    public init(validAddress: Bool?) {
        self.validAddress = validAddress
    }

    public enum CodingKeys: String, CodingKey { 
        case validAddress = "ValidAddress"
    }


}

