//
// FirstNameValidationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request to validate a first name */

public struct FirstNameValidationRequest: Codable {

    /** First name to process */
    public var firstName: String?

    public init(firstName: String?) {
        self.firstName = firstName
    }

    public enum CodingKeys: String, CodingKey { 
        case firstName = "FirstName"
    }


}

