//
// FirstNameValidationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Result of a first name validation operation */
public class FirstNameValidationResponse: JSONEncodable {
    /** True if the validation operation was successful, false otherwise */
    public var successful: Bool?
    /** Possible values are: ValidFirstName, ValidUnknownFirstName, InvalidSpamInput, InvalidCharacters, InvalidEmpty */
    public var validationResult: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Successful"] = self.successful
        nillableDictionary["ValidationResult"] = self.validationResult
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
