//
// FullNameValidationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request to validate a full name string */

public struct FullNameValidationRequest: Codable {

    /** Full name to process as a free-form string; supports many components such as First Name, Middle Name, Last Name, Title, Nickname, Suffix, and Display Name */
    public var fullNameString: String?

    public init(fullNameString: String?) {
        self.fullNameString = fullNameString
    }

    public enum CodingKeys: String, CodingKey { 
        case fullNameString = "FullNameString"
    }


}

