//
// GeolocateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Geolocation result */
public class GeolocateResponse: JSONEncodable {
    /** Two-letter country code of IP address */
    public var countryCode: String?
    /** Country name of IP address */
    public var countryName: String?
    /** City of IP address */
    public var city: String?
    /** State/region code of IP address */
    public var regionCode: String?
    /** State/region of IP address */
    public var regionName: String?
    /** Zip or postal code of IP address */
    public var zipCode: String?
    /** Timezone of IP address */
    public var timezoneStandardName: String?
    /** Latitude of IP address */
    public var latitude: Double?
    /** Longitude of IP address */
    public var longitude: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["CountryCode"] = self.countryCode
        nillableDictionary["CountryName"] = self.countryName
        nillableDictionary["City"] = self.city
        nillableDictionary["RegionCode"] = self.regionCode
        nillableDictionary["RegionName"] = self.regionName
        nillableDictionary["ZipCode"] = self.zipCode
        nillableDictionary["TimezoneStandardName"] = self.timezoneStandardName
        nillableDictionary["Latitude"] = self.latitude
        nillableDictionary["Longitude"] = self.longitude
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
