//
// GeolocateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Geolocation result */

public struct GeolocateResponse: Codable {

    /** Two-letter country code of IP address */
    public var countryCode: String?
    /** Country name of IP address */
    public var countryName: String?
    /** City of IP address */
    public var city: String?
    /** State/region code of IP address */
    public var regionCode: String?
    /** State/region of IP address */
    public var regionName: String?
    /** Zip or postal code of IP address */
    public var zipCode: String?
    /** Timezone of IP address */
    public var timezoneStandardName: String?
    /** Latitude of IP address */
    public var latitude: Double?
    /** Longitude of IP address */
    public var longitude: Double?

    public init(countryCode: String?, countryName: String?, city: String?, regionCode: String?, regionName: String?, zipCode: String?, timezoneStandardName: String?, latitude: Double?, longitude: Double?) {
        self.countryCode = countryCode
        self.countryName = countryName
        self.city = city
        self.regionCode = regionCode
        self.regionName = regionName
        self.zipCode = zipCode
        self.timezoneStandardName = timezoneStandardName
        self.latitude = latitude
        self.longitude = longitude
    }

    public enum CodingKeys: String, CodingKey { 
        case countryCode = "CountryCode"
        case countryName = "CountryName"
        case city = "City"
        case regionCode = "RegionCode"
        case regionName = "RegionName"
        case zipCode = "ZipCode"
        case timezoneStandardName = "TimezoneStandardName"
        case latitude = "Latitude"
        case longitude = "Longitude"
    }


}

