//
// GetGenderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Result of the GetGender operation */

public struct GetGenderResponse: Codable {

    /** True if successful, false otherwise */
    public var successful: Bool?
    /** Gender for this name; possible values are Male, Female, and Neutral (can be applied to Male or Female) */
    public var gender: String?

    public init(successful: Bool?, gender: String?) {
        self.successful = successful
        self.gender = gender
    }

    public enum CodingKeys: String, CodingKey { 
        case successful = "Successful"
        case gender = "Gender"
    }


}

