//
// LastNameValidationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request to validate a last name */

public struct LastNameValidationRequest: Codable {

    /** Last name to process */
    public var lastName: String?

    public init(lastName: String?) {
        self.lastName = lastName
    }

    public enum CodingKeys: String, CodingKey { 
        case lastName = "LastName"
    }


}

