//
// PhoneNumberValidationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Result from validating a phone number */
public class PhoneNumberValidationResponse: JSONEncodable {
    /** True if the phone number is valid, false otherwise */
    public var isValid: Bool?
    /** True if the operation was successful, false if there was an error during validation.  See IsValid for validation result. */
    public var successful: Bool?
    /** Type of phone number; possible values are: FixedLine, Mobile, FixedLineOrMobile, TollFree, PremiumRate,   SharedCost, Voip, PersonalNumber, Pager, Uan, Voicemail, Unknown */
    public var phoneNumberType: String?
    /** E.164 format of the phone number */
    public var e164Format: String?
    /** Internaltional format of the phone number */
    public var internationalFormat: String?
    /** National format of the phone number */
    public var nationalFormat: String?
    /** Two digit country code of the phone number */
    public var countryCode: String?
    /** User-friendly long name of the country for the phone number */
    public var countryName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["IsValid"] = self.isValid
        nillableDictionary["Successful"] = self.successful
        nillableDictionary["PhoneNumberType"] = self.phoneNumberType
        nillableDictionary["E164Format"] = self.e164Format
        nillableDictionary["InternationalFormat"] = self.internationalFormat
        nillableDictionary["NationalFormat"] = self.nationalFormat
        nillableDictionary["CountryCode"] = self.countryCode
        nillableDictionary["CountryName"] = self.countryName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
