//
// PhoneNumberValidateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request to validate a phone number */

public struct PhoneNumberValidateRequest: Codable {

    /** Raw phone number string to parse as input for validation */
    public var phoneNumber: String?
    /** Optional, default country code.  If left blank, will default to \&quot;US\&quot;. */
    public var defaultCountryCode: String?

    public init(phoneNumber: String?, defaultCountryCode: String?) {
        self.phoneNumber = phoneNumber
        self.defaultCountryCode = defaultCountryCode
    }

    public enum CodingKeys: String, CodingKey { 
        case phoneNumber = "PhoneNumber"
        case defaultCountryCode = "DefaultCountryCode"
    }


}

