//
// PhoneNumberValidateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request to validate a phone number */
public class PhoneNumberValidateRequest: JSONEncodable {
    /** Raw phone number string to parse as input for validation */
    public var phoneNumber: String?
    /** Optional, default country code.  If left blank, will default to \&quot;US\&quot;. */
    public var defaultCountryCode: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["PhoneNumber"] = self.phoneNumber
        nillableDictionary["DefaultCountryCode"] = self.defaultCountryCode
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
