//
// VatLookupResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VatLookupResponse: Codable {

    public var countryCode: String?
    public var vatNumber: String?
    public var isValid: Bool?
    public var businessName: String?
    public var businessAddress: String?

    public init(countryCode: String?, vatNumber: String?, isValid: Bool?, businessName: String?, businessAddress: String?) {
        self.countryCode = countryCode
        self.vatNumber = vatNumber
        self.isValid = isValid
        self.businessName = businessName
        self.businessAddress = businessAddress
    }

    public enum CodingKeys: String, CodingKey { 
        case countryCode = "CountryCode"
        case vatNumber = "VatNumber"
        case isValid = "IsValid"
        case businessName = "BusinessName"
        case businessAddress = "BusinessAddress"
    }


}

