//
// VatLookupRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Input to a VAT lookup request */

public struct VatLookupRequest: Codable {

    public var vatCode: String?

    public init(vatCode: String?) {
        self.vatCode = vatCode
    }

    public enum CodingKeys: String, CodingKey { 
        case vatCode = "VatCode"
    }


}

