//
// VatLookupResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class VatLookupResponse: JSONEncodable {
    public var countryCode: String?
    public var vatNumber: String?
    public var isValid: Bool?
    public var businessName: String?
    public var businessAddress: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["CountryCode"] = self.countryCode
        nillableDictionary["VatNumber"] = self.vatNumber
        nillableDictionary["IsValid"] = self.isValid
        nillableDictionary["BusinessName"] = self.businessName
        nillableDictionary["BusinessAddress"] = self.businessAddress
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
