//
// WhoisResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Result of a WHOIS operation */

public struct WhoisResponse: Codable {

    /** True if the domain is valid, false if it is not */
    public var validDomain: Bool?
    /** Server used to lookup WHOIS information (may change based on lookup). */
    public var whoisServer: String?
    /** WHOIS raw text record */
    public var rawTextRecord: String?
    /** Creation date for the record */
    public var createdDt: Date?

    public init(validDomain: Bool?, whoisServer: String?, rawTextRecord: String?, createdDt: Date?) {
        self.validDomain = validDomain
        self.whoisServer = whoisServer
        self.rawTextRecord = rawTextRecord
        self.createdDt = createdDt
    }

    public enum CodingKeys: String, CodingKey { 
        case validDomain = "ValidDomain"
        case whoisServer = "WhoisServer"
        case rawTextRecord = "RawTextRecord"
        case createdDt = "CreatedDt"
    }


}

