//
// WhoisResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Result of a WHOIS operation */
public class WhoisResponse: JSONEncodable {
    /** True if the domain is valid, false if it is not */
    public var validDomain: Bool?
    /** Server used to lookup WHOIS information (may change based on lookup). */
    public var whoisServer: String?
    /** WHOIS raw text record */
    public var rawTextRecord: String?
    /** Creation date for the record */
    public var createdDt: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ValidDomain"] = self.validDomain
        nillableDictionary["WhoisServer"] = self.whoisServer
        nillableDictionary["RawTextRecord"] = self.rawTextRecord
        nillableDictionary["CreatedDt"] = self.createdDt?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
