//
// DomainAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class DomainAPI: APIBase {
    /**
     Validate a domain name
     
     - parameter domain: (body) Domain name to check, for example \&quot;cloudmersive.com\&quot;.  The input is a string so be sure to enclose it in double-quotes. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func domainCheck(domain domain: String, completion: ((data: CheckResponse?, error: ErrorType?) -> Void)) {
        domainCheckWithRequestBuilder(domain: domain).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Validate a domain name
     - POST /validate/domain/check
     - Check whether a domain name is valid or not.  API performs a live validation by contacting DNS services to validate the existence of the domain name.
     - API Key:
       - type: apiKey Apikey 
       - name: Apikey
     - examples: [{contentType=application/json, example={
  "ValidDomain" : true
}}, {contentType=application/xml, example=<null>
  <ValidDomain>true</ValidDomain>
</null>}]
     - examples: [{contentType=application/json, example={
  "ValidDomain" : true
}}, {contentType=application/xml, example=<null>
  <ValidDomain>true</ValidDomain>
</null>}]
     
     - parameter domain: (body) Domain name to check, for example \&quot;cloudmersive.com\&quot;.  The input is a string so be sure to enclose it in double-quotes. 

     - returns: RequestBuilder<CheckResponse> 
     */
    public class func domainCheckWithRequestBuilder(domain domain: String) -> RequestBuilder<CheckResponse> {
        let path = "/validate/domain/check"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = domain.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<CheckResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get WHOIS information for a domain
     
     - parameter domain: (body) Domain name to check, for example \&quot;cloudmersive.com\&quot;.   The input is a string so be sure to enclose it in double-quotes. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func domainPost(domain domain: String, completion: ((data: WhoisResponse?, error: ErrorType?) -> Void)) {
        domainPostWithRequestBuilder(domain: domain).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get WHOIS information for a domain
     - POST /validate/domain/whois
     - Validate whether a domain name exists, and also return the full WHOIS record for that domain name.  WHOIS records include all the registration details of the domain name, such as information about the domain's owners.
     - API Key:
       - type: apiKey Apikey 
       - name: Apikey
     - examples: [{contentType=application/json, example={
  "WhoisServer" : "WhoisServer",
  "CreatedDt" : "2000-01-23T04:56:07.000+00:00",
  "ValidDomain" : true,
  "RawTextRecord" : "RawTextRecord"
}}, {contentType=application/xml, example=<null>
  <ValidDomain>true</ValidDomain>
  <WhoisServer>aeiou</WhoisServer>
  <RawTextRecord>aeiou</RawTextRecord>
  <CreatedDt>2000-01-23T04:56:07.000Z</CreatedDt>
</null>}]
     - examples: [{contentType=application/json, example={
  "WhoisServer" : "WhoisServer",
  "CreatedDt" : "2000-01-23T04:56:07.000+00:00",
  "ValidDomain" : true,
  "RawTextRecord" : "RawTextRecord"
}}, {contentType=application/xml, example=<null>
  <ValidDomain>true</ValidDomain>
  <WhoisServer>aeiou</WhoisServer>
  <RawTextRecord>aeiou</RawTextRecord>
  <CreatedDt>2000-01-23T04:56:07.000Z</CreatedDt>
</null>}]
     
     - parameter domain: (body) Domain name to check, for example \&quot;cloudmersive.com\&quot;.   The input is a string so be sure to enclose it in double-quotes. 

     - returns: RequestBuilder<WhoisResponse> 
     */
    public class func domainPostWithRequestBuilder(domain domain: String) -> RequestBuilder<WhoisResponse> {
        let path = "/validate/domain/whois"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = domain.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<WhoisResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
