//
// IPAddressAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class IPAddressAPI {
    /**
     Geolocate an IP address
     
     - parameter value: (body) IP address to geolocate, e.g. \&quot;55.55.55.55\&quot;.  The input is a string so be sure to enclose it in double-quotes. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func iPAddressPost(value: String, completion: @escaping ((_ data: GeolocateResponse?,_ error: Error?) -> Void)) {
        iPAddressPostWithRequestBuilder(value: value).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Geolocate an IP address
     - POST /validate/ip/geolocate
     - Identify an IP address Country, State/Provence, City, Zip/Postal Code, etc.  Useful for security and UX applications.
     - API Key:
       - type: apiKey Apikey 
       - name: Apikey
     - examples: [{contentType=application/json, example={
  "RegionCode" : "RegionCode",
  "CountryName" : "CountryName",
  "RegionName" : "RegionName",
  "ZipCode" : "ZipCode",
  "TimezoneStandardName" : "TimezoneStandardName",
  "Latitude" : 0.8008281904610115,
  "City" : "City",
  "CountryCode" : "CountryCode",
  "Longitude" : 6.027456183070403
}}, {contentType=application/xml, example=<null>
  <CountryCode>aeiou</CountryCode>
  <CountryName>aeiou</CountryName>
  <City>aeiou</City>
  <RegionCode>aeiou</RegionCode>
  <RegionName>aeiou</RegionName>
  <ZipCode>aeiou</ZipCode>
  <TimezoneStandardName>aeiou</TimezoneStandardName>
  <Latitude>3.149</Latitude>
  <Longitude>3.149</Longitude>
</null>}]
     - examples: [{contentType=application/json, example={
  "RegionCode" : "RegionCode",
  "CountryName" : "CountryName",
  "RegionName" : "RegionName",
  "ZipCode" : "ZipCode",
  "TimezoneStandardName" : "TimezoneStandardName",
  "Latitude" : 0.8008281904610115,
  "City" : "City",
  "CountryCode" : "CountryCode",
  "Longitude" : 6.027456183070403
}}, {contentType=application/xml, example=<null>
  <CountryCode>aeiou</CountryCode>
  <CountryName>aeiou</CountryName>
  <City>aeiou</City>
  <RegionCode>aeiou</RegionCode>
  <RegionName>aeiou</RegionName>
  <ZipCode>aeiou</ZipCode>
  <TimezoneStandardName>aeiou</TimezoneStandardName>
  <Latitude>3.149</Latitude>
  <Longitude>3.149</Longitude>
</null>}]
     
     - parameter value: (body) IP address to geolocate, e.g. \&quot;55.55.55.55\&quot;.  The input is a string so be sure to enclose it in double-quotes. 

     - returns: RequestBuilder<GeolocateResponse> 
     */
    open class func iPAddressPostWithRequestBuilder(value: String) -> RequestBuilder<GeolocateResponse> {
        let path = "/validate/ip/geolocate"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: value)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<GeolocateResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
