//
// NameAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class NameAPI {
    /**
     Get the gender of a first name
     
     - parameter input: (body) Gender request information 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func nameGetGender(input: GetGenderRequest, completion: @escaping ((_ data: GetGenderResponse?,_ error: Error?) -> Void)) {
        nameGetGenderWithRequestBuilder(input: input).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get the gender of a first name
     - POST /validate/name/get-gender
     - Determines the gender of a first name (given name)
     - API Key:
       - type: apiKey Apikey 
       - name: Apikey
     - examples: [{contentType=application/json, example={
  "Gender" : "Gender",
  "Successful" : true
}}, {contentType=application/xml, example=<null>
  <Successful>true</Successful>
  <Gender>aeiou</Gender>
</null>}]
     - examples: [{contentType=application/json, example={
  "Gender" : "Gender",
  "Successful" : true
}}, {contentType=application/xml, example=<null>
  <Successful>true</Successful>
  <Gender>aeiou</Gender>
</null>}]
     
     - parameter input: (body) Gender request information 

     - returns: RequestBuilder<GetGenderResponse> 
     */
    open class func nameGetGenderWithRequestBuilder(input: GetGenderRequest) -> RequestBuilder<GetGenderResponse> {
        let path = "/validate/name/get-gender"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: input)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<GetGenderResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Validate a first name
     
     - parameter input: (body) Validation request information 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func nameValidateFirstName(input: FirstNameValidationRequest, completion: @escaping ((_ data: FirstNameValidationResponse?,_ error: Error?) -> Void)) {
        nameValidateFirstNameWithRequestBuilder(input: input).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Validate a first name
     - POST /validate/name/first
     - Determines if a string is a valid first name (given name)
     - API Key:
       - type: apiKey Apikey 
       - name: Apikey
     - examples: [{contentType=application/json, example={
  "ValidationResult" : "ValidationResult",
  "Successful" : true
}}, {contentType=application/xml, example=<null>
  <Successful>true</Successful>
  <ValidationResult>aeiou</ValidationResult>
</null>}]
     - examples: [{contentType=application/json, example={
  "ValidationResult" : "ValidationResult",
  "Successful" : true
}}, {contentType=application/xml, example=<null>
  <Successful>true</Successful>
  <ValidationResult>aeiou</ValidationResult>
</null>}]
     
     - parameter input: (body) Validation request information 

     - returns: RequestBuilder<FirstNameValidationResponse> 
     */
    open class func nameValidateFirstNameWithRequestBuilder(input: FirstNameValidationRequest) -> RequestBuilder<FirstNameValidationResponse> {
        let path = "/validate/name/first"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: input)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<FirstNameValidationResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Parse and validate a full name
     
     - parameter input: (body) Validation request information 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func nameValidateFullName(input: FullNameValidationRequest, completion: @escaping ((_ data: FullNameValidationResponse?,_ error: Error?) -> Void)) {
        nameValidateFullNameWithRequestBuilder(input: input).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Parse and validate a full name
     - POST /validate/name/full-name
     - Parses a full name string (e.g. \"Mr. Jon van der Waal Jr.\") into its component parts (and returns these component parts), and then validates whether it is a valid name string or not
     - API Key:
       - type: apiKey Apikey 
       - name: Apikey
     - examples: [{contentType=application/json, example={
  "Suffix" : "Suffix",
  "ValidationResult_LastName" : "ValidationResult_LastName",
  "FirstName" : "FirstName",
  "ValidationResult_FirstName" : "ValidationResult_FirstName",
  "DisplayName" : "DisplayName",
  "Title" : "Title",
  "LastName" : "LastName",
  "MiddleName" : "MiddleName",
  "NickName" : "NickName",
  "Successful" : true
}}, {contentType=application/xml, example=<null>
  <Successful>true</Successful>
  <ValidationResult_FirstName>aeiou</ValidationResult_FirstName>
  <ValidationResult_LastName>aeiou</ValidationResult_LastName>
  <Title>aeiou</Title>
  <FirstName>aeiou</FirstName>
  <MiddleName>aeiou</MiddleName>
  <LastName>aeiou</LastName>
  <NickName>aeiou</NickName>
  <Suffix>aeiou</Suffix>
  <DisplayName>aeiou</DisplayName>
</null>}]
     - examples: [{contentType=application/json, example={
  "Suffix" : "Suffix",
  "ValidationResult_LastName" : "ValidationResult_LastName",
  "FirstName" : "FirstName",
  "ValidationResult_FirstName" : "ValidationResult_FirstName",
  "DisplayName" : "DisplayName",
  "Title" : "Title",
  "LastName" : "LastName",
  "MiddleName" : "MiddleName",
  "NickName" : "NickName",
  "Successful" : true
}}, {contentType=application/xml, example=<null>
  <Successful>true</Successful>
  <ValidationResult_FirstName>aeiou</ValidationResult_FirstName>
  <ValidationResult_LastName>aeiou</ValidationResult_LastName>
  <Title>aeiou</Title>
  <FirstName>aeiou</FirstName>
  <MiddleName>aeiou</MiddleName>
  <LastName>aeiou</LastName>
  <NickName>aeiou</NickName>
  <Suffix>aeiou</Suffix>
  <DisplayName>aeiou</DisplayName>
</null>}]
     
     - parameter input: (body) Validation request information 

     - returns: RequestBuilder<FullNameValidationResponse> 
     */
    open class func nameValidateFullNameWithRequestBuilder(input: FullNameValidationRequest) -> RequestBuilder<FullNameValidationResponse> {
        let path = "/validate/name/full-name"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: input)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<FullNameValidationResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Validate a last name
     
     - parameter input: (body) Validation request information 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func nameValidateLastName(input: LastNameValidationRequest, completion: @escaping ((_ data: LastNameValidationResponse?,_ error: Error?) -> Void)) {
        nameValidateLastNameWithRequestBuilder(input: input).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Validate a last name
     - POST /validate/name/last
     - Determines if a string is a valid last name (surname)
     - API Key:
       - type: apiKey Apikey 
       - name: Apikey
     - examples: [{contentType=application/json, example={
  "ValidationResult" : "ValidationResult",
  "Successful" : true
}}, {contentType=application/xml, example=<null>
  <Successful>true</Successful>
  <ValidationResult>aeiou</ValidationResult>
</null>}]
     - examples: [{contentType=application/json, example={
  "ValidationResult" : "ValidationResult",
  "Successful" : true
}}, {contentType=application/xml, example=<null>
  <Successful>true</Successful>
  <ValidationResult>aeiou</ValidationResult>
</null>}]
     
     - parameter input: (body) Validation request information 

     - returns: RequestBuilder<LastNameValidationResponse> 
     */
    open class func nameValidateLastNameWithRequestBuilder(input: LastNameValidationRequest) -> RequestBuilder<LastNameValidationResponse> {
        let path = "/validate/name/last"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: input)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<LastNameValidationResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
