//
// PhoneNumberAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class PhoneNumberAPI {
    /**
     Validate phone number (basic)
     
     - parameter value: (body) Phone number to validate in a PhoneNumberValidateRequest object.  Try a phone number such as \&quot;1.800.463.3339\&quot;, and either leave DefaultCountryCode blank or use \&quot;US\&quot;. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func phoneNumberSyntaxOnly(value: PhoneNumberValidateRequest, completion: @escaping ((_ data: PhoneNumberValidationResponse?,_ error: Error?) -> Void)) {
        phoneNumberSyntaxOnlyWithRequestBuilder(value: value).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Validate phone number (basic)
     - POST /validate/phonenumber/basic
     - Validate a phone number by analyzing the syntax
     - API Key:
       - type: apiKey Apikey 
       - name: Apikey
     - examples: [{contentType=application/json, example={
  "InternationalFormat" : "InternationalFormat",
  "NationalFormat" : "NationalFormat",
  "CountryName" : "CountryName",
  "E164Format" : "E164Format",
  "CountryCode" : "CountryCode",
  "Successful" : true,
  "PhoneNumberType" : "PhoneNumberType",
  "IsValid" : true
}}, {contentType=application/xml, example=<null>
  <IsValid>true</IsValid>
  <Successful>true</Successful>
  <PhoneNumberType>aeiou</PhoneNumberType>
  <E164Format>aeiou</E164Format>
  <InternationalFormat>aeiou</InternationalFormat>
  <NationalFormat>aeiou</NationalFormat>
  <CountryCode>aeiou</CountryCode>
  <CountryName>aeiou</CountryName>
</null>}]
     - examples: [{contentType=application/json, example={
  "InternationalFormat" : "InternationalFormat",
  "NationalFormat" : "NationalFormat",
  "CountryName" : "CountryName",
  "E164Format" : "E164Format",
  "CountryCode" : "CountryCode",
  "Successful" : true,
  "PhoneNumberType" : "PhoneNumberType",
  "IsValid" : true
}}, {contentType=application/xml, example=<null>
  <IsValid>true</IsValid>
  <Successful>true</Successful>
  <PhoneNumberType>aeiou</PhoneNumberType>
  <E164Format>aeiou</E164Format>
  <InternationalFormat>aeiou</InternationalFormat>
  <NationalFormat>aeiou</NationalFormat>
  <CountryCode>aeiou</CountryCode>
  <CountryName>aeiou</CountryName>
</null>}]
     
     - parameter value: (body) Phone number to validate in a PhoneNumberValidateRequest object.  Try a phone number such as \&quot;1.800.463.3339\&quot;, and either leave DefaultCountryCode blank or use \&quot;US\&quot;. 

     - returns: RequestBuilder<PhoneNumberValidationResponse> 
     */
    open class func phoneNumberSyntaxOnlyWithRequestBuilder(value: PhoneNumberValidateRequest) -> RequestBuilder<PhoneNumberValidationResponse> {
        let path = "/validate/phonenumber/basic"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: value)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<PhoneNumberValidationResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
