//
// VatAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class VatAPI {
    /**
     Lookup a VAT code
     
     - parameter input: (body) Input VAT code 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func vatVatLookup(input: VatLookupRequest, completion: @escaping ((_ data: VatLookupResponse?,_ error: Error?) -> Void)) {
        vatVatLookupWithRequestBuilder(input: input).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Lookup a VAT code
     - POST /validate/vat/lookup
     - Checks if a VAT code is valid, and if it is, returns more information about it
     - API Key:
       - type: apiKey Apikey 
       - name: Apikey
     - examples: [{contentType=application/json, example={
  "BusinessName" : "BusinessName",
  "CountryCode" : "CountryCode",
  "VatNumber" : "VatNumber",
  "BusinessAddress" : "BusinessAddress",
  "IsValid" : true
}}, {contentType=application/xml, example=<null>
  <CountryCode>aeiou</CountryCode>
  <VatNumber>aeiou</VatNumber>
  <IsValid>true</IsValid>
  <BusinessName>aeiou</BusinessName>
  <BusinessAddress>aeiou</BusinessAddress>
</null>}]
     - examples: [{contentType=application/json, example={
  "BusinessName" : "BusinessName",
  "CountryCode" : "CountryCode",
  "VatNumber" : "VatNumber",
  "BusinessAddress" : "BusinessAddress",
  "IsValid" : true
}}, {contentType=application/xml, example=<null>
  <CountryCode>aeiou</CountryCode>
  <VatNumber>aeiou</VatNumber>
  <IsValid>true</IsValid>
  <BusinessName>aeiou</BusinessName>
  <BusinessAddress>aeiou</BusinessAddress>
</null>}]
     
     - parameter input: (body) Input VAT code 

     - returns: RequestBuilder<VatLookupResponse> 
     */
    open class func vatVatLookupWithRequestBuilder(input: VatLookupRequest) -> RequestBuilder<VatLookupResponse> {
        let path = "/validate/vat/lookup"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: input)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<VatLookupResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
