//
// VatAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class VatAPI: APIBase {
    /**
     Lookup a VAT code
     
     - parameter input: (body) Input VAT code 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func vatVatLookup(input input: VatLookupRequest, completion: ((data: VatLookupResponse?, error: ErrorType?) -> Void)) {
        vatVatLookupWithRequestBuilder(input: input).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Lookup a VAT code
     - POST /validate/vat/lookup
     - Checks if a VAT code is valid, and if it is, returns more information about it
     - API Key:
       - type: apiKey Apikey 
       - name: Apikey
     - examples: [{contentType=application/json, example={
  "BusinessName" : "BusinessName",
  "CountryCode" : "CountryCode",
  "VatNumber" : "VatNumber",
  "BusinessAddress" : "BusinessAddress",
  "IsValid" : true
}}, {contentType=application/xml, example=<null>
  <CountryCode>aeiou</CountryCode>
  <VatNumber>aeiou</VatNumber>
  <IsValid>true</IsValid>
  <BusinessName>aeiou</BusinessName>
  <BusinessAddress>aeiou</BusinessAddress>
</null>}]
     - examples: [{contentType=application/json, example={
  "BusinessName" : "BusinessName",
  "CountryCode" : "CountryCode",
  "VatNumber" : "VatNumber",
  "BusinessAddress" : "BusinessAddress",
  "IsValid" : true
}}, {contentType=application/xml, example=<null>
  <CountryCode>aeiou</CountryCode>
  <VatNumber>aeiou</VatNumber>
  <IsValid>true</IsValid>
  <BusinessName>aeiou</BusinessName>
  <BusinessAddress>aeiou</BusinessAddress>
</null>}]
     
     - parameter input: (body) Input VAT code 

     - returns: RequestBuilder<VatLookupResponse> 
     */
    public class func vatVatLookupWithRequestBuilder(input input: VatLookupRequest) -> RequestBuilder<VatLookupResponse> {
        let path = "/validate/vat/lookup"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = input.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<VatLookupResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
